### ISSUE TITLE
”Hello World”, foundation.

### ISSUE THREAD

**Issue by altetmek** [DIT112-V20/group-03#10]
- As a developer, I want to have a foundation for the web application, so that I can start expanding on its functionalities.

**Comment by altetmek** [comment]
Requirements to be covered with this issue (NEW):

- The website should have the basic display, “Hello World”.

- The website should be accessible by all members, and only for the members to work on (Constraint).

**Comment by altetmek** [comment]
This issue is only to kick start the milestone [web application](https://github.com/DIT112-V20/group-03/milestone/6) to have some foundation to be able to work with the web application

**Comment by leithhobson** [comment]
This issue was resolved in 87e94a8
