### ISSUE TITLE
Basic Movement

### ISSUE THREAD

**Issue by altetmek** [DIT112-V20/group-03#12]
- As a user, I want the car to be able to move forward, backward, left and right, so that the car can perform the basic needs/functions of a car.

- As a developer, I want the car to perform the basic movements, so that I can start working on the more elaborate functions of it such as [collision avoidance](https://github.com/DIT112-V20/group-03/milestone/5) and [obstacle avoidance](https://github.com/DIT112-V20/group-03/milestone/10)

**Comment by altetmek** [comment]
Requirements to be covered with this issue:

- The car should be able to go forward and backwards. 

- The car should be able to turn left and right. 

- The car should be able to brake.

**Comment by leithhobson** [comment]
This issue was resolved in PR #15
