### ISSUE TITLE
[Web Application] - Auto redirect to HTTPS

### ISSUE THREAD

**Issue by leithhobson** [DIT112-V20/group-03#35]
As a user, I want the application to automatically redirect me from http to https

**Comment by altetmek** [comment]
We have moved this issue to Sprint#3 as we are only now able to fix it.

**Comment by leithhobson** [comment]
This issue was originally resolved in #36 however, was left open due to it seemingly not working.
The issue is however related to the application not running with root privileges on the server (which we do not want it to have)

This is therefore resolved by running the following commands as root (in our case we are running an Ubuntu 20.04 server, however, these commands will differ accroding to your hosting enviroment), which will internally forward the relevant ports.

`iptables -A INPUT -i eth0 -p tcp --dport 80 -j ACCEPT`
`iptables -A INPUT -i eth0 -p tcp --dport 443 -j ACCEPT`
`iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8080`
`iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 443 -j REDIRECT --to-port 8443`

- You should also ensure that the relevant ports are open in your firewall
