### ISSUE TITLE
Personal and "dev" branches

### ISSUE THREAD

**Issue by platisd** [DIT112-V20/group-03#39]
What is the idea behind your personal branches as well the `dev` one? This practice is generally considered a red flag :red_circle: .

From what I have seen, you are merging to `dev` without any code reviews (e.g #37, #32) and at some point you do large(r) merges to `master` which naturally cannot be code-reviewed as effectively.

If you are doing this to get around the need of having to code review, I will add compulsory code reviews for the `dev` branch too. :scream: 
¯\_(ツ)_/¯

**Comment by leithhobson** [comment]
@platisd I discuss with you later, as we are currently in a team meeting, however, I was going to ask you to add the compulsory reviews on the dev branch anyway :)

**Comment by platisd** [comment]
> I was going to ask you to add the compulsory reviews on the dev branch anyway

The biggest question of them all is why have a `dev` branch in the first place! :grinning:

**Comment by leithhobson** [comment]
Hi @platisd 

The reason that we have a dev branch is that we have agreed on criteria that would constitute a 'finished' project, but further, on criteria that we would like to implement, if we have time (but which may likely never be completed).

We are therefore working in the industry way where the dev branch is the upcoming version, while the master branch is (once we get our first working version) always a stable 'release' version, as would be deployed on production application servers, and cars.

So, therefore, we will have large pull requests from dev to master, that will contain all features that have been developed up to the point of the next release, while we will have continuous PRs from personal branches in dev, and everyone is continuously merging dev into their own branch.

This is not to get away from the code reviews, and, as I said, we had intended to ask you to make them compulsory on the dev branch. We will also further have our own CI rules, that will, once implemented prevent merges with code that does not have sufficient unit test coverage, or where unit tests are failing. We are further investigating CI rules that will block merges where individual commit comments do not follow a certain pattern.

If you believe this is not in order, we will happily eliminate the dev branch.

**Comment by platisd** [comment]
Didn't have time to answer this yesterday but I did not forget about it! :grin: 

> We are therefore working in the industry way where the dev branch is the upcoming version, while the master branch is (once we get our first working version) always a stable 'release' version, as would be deployed on production application servers, and cars.

This is **not** the industry way, or at least the _modern_ industry way. It's waterfall actually. It usually implies a technical debt in testing, which means that testing to see whether new software is good enough is slow.  For example, there may be no automated tests, automated tests do not cover the entire functionality and/or those that exist are slow. There may be also other objective difficulties in deploying new software (e.g. there is no connectivity) or there are regulations in place.

I understand the need for such branching policy in some industrial projects, especially when they have been going on for a while and they are large in a very complicated domain.
However, in your case, you are starting from scratch, with a small team and your project will be very simple compared to a car or an operating system. Why follow a practice that is considered a _necessary evil_ wherever it is adopted and organizations are generally trying to move away from it? Why even establish such a process from the beginning of a project without even trying things "the right way" (and yes, it *is* the right/modern way)?

What often happens, which is not as bad as a `dev` branch (but is not the best practice either), are *release* branches which are spun off from the `master`. Development takes place on `master` and by time to time, a new branch is created (and supported for a time) *from* the `master` which is delivered to customers. Then there may be release-specific bugfixes and what-not, but ideally, you want everyone to use your latest software that is also the greatest since you have invested in a continuous quality assurance process.

Considering the above, I'd insist on ditching the `dev` branch. It will make your lives easier.
