### ISSUE TITLE
[Web Application] Create Database and connect web application

### ISSUE THREAD

**Issue by altetmek** [DIT112-V20/group-03#42]
As a recurring driver, I want the web application to be connected to a database, so that my data is saved for later use to give a better experience.

**Comment by altetmek** [comment]
Additional requirements that will be covered with this issue:

- The web applications should be able to persistently store users and cars in the database.

**Comment by platisd** [comment]
Developers are not users of the system. Try to map what needs to be done with some business value. For example, if you want to create a database, then try to illustrate how this database helps the <x> user achieve what they want.
