### ISSUE TITLE
[Create API in the web application] - Finish this milestone.

### ISSUE THREAD

**Issue by altetmek** [DIT112-V20/group-03#43]
As a father who's gifting the car to his son, I want the website to implement a fully working API, so that my commands are forwarded to the car.

As the son who is recieving the car as a gift from his father, I want the car to recognize my commands via the web application, so that I can use the application for the car.

**Comment by altetmek** [comment]
Additional requirements that will be covered with this issue:

-

**Comment by altetmek** [comment]
Closing this issue was a mistake.

**Comment by platisd** [comment]
Try to find a more specific "name" for your 'user'. Who are your users?
