### ISSUE TITLE
Acquire FTDI

### ISSUE THREAD

**Issue by leithhobson** [DIT112-V20/group-03#48]
We received our ESP32 cam this morning (the one that @platisd indicated), however, there is no onboard usb port, and so we need an FTDI converter.

I have previously seen where one can bridge the relevant ports between one board with an onboard FTDI, and one without, and both boards are programmed simultaneously, however, I do not wish to risk damaging either board.

@platisd, might you be able to lend us an FTDI, or your guidance on bridging the two boards, if you have experience with this?

**Comment by platisd** [comment]
I think I have one that works with 3.3V, so you can have it.
Alternatively, I was in any case planning to order one of [these](https://www.tindie.com/products/bitluni/cam-prog/) once my cameras would arrive from China. I will order a couple of them today, so if you can wait until I receive them from Germany, you can have those instead which would be much easier to use.

**Comment by leithhobson** [comment]
> 
> 
> I think I have one that works with 3.3V, so you can have it.
> Alternatively, I was in any case planning to order one of [these](https://www.tindie.com/products/bitluni/cam-prog/) once my cameras would arrive from China. I will order a couple of them today, so if you can wait until I receive them, you can have those instead which would be much easier to use.

Thank you very much, we can wait for the cam-prog from tindie, however, if they take rather long to arrive, we may ask for the 3.3V compatible one that you have.

**Comment by platisd** [comment]
Alright, I've ordered the Tindie modules. They come from Germany, which usually means things take less than a week to arrive. That being said, I am not sure how Easter + Corona will affect the situation. I'll keep you updated.

**Comment by leithhobson** [comment]
A week or two will be no issue (although, we may have to check if we need to reshuffle our planned schedule acordingly)

Thank you very much

**Comment by platisd** [comment]
Let's meet on Wednesday after lunch. Say 14:00?
If the programmers have arrived I'll give you one of them. Otherwise I'll give you an USB-to-Serial module. Does Korsvagen or Molndal work for you?

**Comment by leithhobson** [comment]
Perfect, that will work.
Either works. I assume you're probably closer to Mölndal, so I can come out there (but whichever is closer for yourself).

**Comment by platisd** [comment]
I am slightly closer to Mölndal, indeed. Let's meet at the terminal tram stop at 14:00

**Comment by leithhobson** [comment]
Just confirming that I will be there at 14 :)

**Comment by platisd** [comment]
Yeap, received the programmers so I'll give you one of them. :+1:

**Comment by diaistanbuly** [comment]
Leith is at Mölndal innerstad, tram stop A

**Comment by leithhobson** [comment]
Thank you @platisd
