### ISSUE TITLE
[Connect Car to the Internet] - Complete this milestone

### ISSUE THREAD

**Issue by altetmek** [DIT112-V20/group-03#49]
As a person who wants to avoid personal contact, I want to be able to operate the car remotely, so that I can avoid personal contact, if the car is allowed to be controlled via the internet.

as a person who does not have a physical access to the car, I want to be able to access the car using an internet connection, I can operate the car remotely.

**Comment by altetmek** [comment]
Additional Requirements that will be covered with this issue:

- The car should be able establish a connection with the internet.

**Comment by leithhobson** [comment]
Resolved in aff8775
