### ISSUE TITLE
[WebApplication] - Write unit tests for code writen thus far

### ISSUE THREAD

**Issue by leithhobson** [DIT112-V20/group-03#55]
As a car driver, I want the peace of mind that all code has been automatically tested so that I can relax while driving.

**Comment by altetmek** [comment]
Commits [79725ce](https://github.com/DIT112-V20/group-03/commit/79725ceee1727a7867660f4a56d67c30046a7a69), and [d84de52](https://github.com/DIT112-V20/group-03/commit/d84de5217b49e0f3d5607c75d97e8bc49c6fe1b6) has resolved this issue.
