### ISSUE TITLE
[CI] - Unit test line coverage

### ISSUE THREAD

**Issue by leithhobson** [DIT112-V20/group-03#58]
As a car owner, I want the peace of mind that all new code is automatically built by a CI framework and the assurity that these tests cover as much code as possible so that I can be relaxed when using the application.

**Comment by platisd** [comment]
Try [codecov.io](https://codecov.io/)

**Comment by leithhobson** [comment]
> Try [codecov.io](https://codecov.io/)

I understand this to only be free for teams up to 5, but we are larger, and so we can not (legally atleast) use the service without a license

Or, perhaps I am mistaken?

**Comment by platisd** [comment]
I am 99% sure that by "users" they refer to codecov account administrators. In your case, especially since it's open source, there won't be a problem.

**Comment by altetmek** [comment]
Commits 79725ce, and d84de52 has partially resolved this issue. We deem the line coverage sufficient considering the time restraints.
