### ISSUE TITLE
[WebApplication] - Obstacle avoidance notification

### ISSUE THREAD

**Issue by leithhobson** [DIT112-V20/group-03#79]
As a user, I want to be notified when the car that I am driving avoids an obstacle or collision, so that I do not get frustrated if it does not follow my commands during this time.

**Comment by altetmek** [comment]
This is done.

**Comment by platisd** [comment]
Ideally, we should be also able to tell **where in the code** this was done. :)

**Comment by diaistanbuly** [comment]
The code is in my local branch, will be merged in the beginning of a working day, which is Monday :)

**Comment by platisd** [comment]
Then it's not done and therefore this issue should not be closed.
