### ISSUE TITLE
Enable the car to recognize the distance between it and an obstacle.

### ISSUE THREAD

**Issue by altetmek** [DIT112-V20/group-03#8]
- As a developer, I want the car to be able to recognize the distance to an incoming obstacle, so that I can command it to take an appropriate action.

- As a user, I want the car to be aware of the distance to a closing obstacle, so that the car can take appropriate action in case I am unable to.

**Comment by filiplew** [comment]
Requirement to be covered for this Issue:

- The car should be able to detect when it is about to run into an obstacle.

**Comment by leithhobson** [comment]
This issue was resolved in PR #15
