### ISSUE TITLE
Make the car stop at a distance of our choosing after detecting an obstacle

### ISSUE THREAD

**Issue by altetmek** [DIT112-V20/group-03#9]
- As a developer, I want the car to stop before colliding with an obstacle, so that the hardware doesn't get damaged.

- As a user, I want the car to stop when getting close to an obstacle, so that I can decide which action it will take next.

**Comment by filiplew** [comment]
Requirement to be covered with this issue:

- When the car detects something it will collide with, it should be able to prevent it from happening by braking(See the “Basic Movement” milestone).

**Comment by leithhobson** [comment]
This issue was resolved in PR #15
